### ISSUE TITLE
In Graphql total count of filtered items is wrong

### ISSUE THREAD

**Issue by Caio-Mendonca** [DomDew/strapi-plugin-fuzzy-search#104]
I'm building a blog and when I bring in my filtered data with Search I get an incorrect return of the quantity that refers to my filter.

![Screenshot 2023-11-03 at 9 28 41 AM](https://github.com/DomDew/strapi-plugin-fuzzy-search/assets/84800849/e9f0a7f0-abdf-4865-adf3-4eea9a274db8)

In the example in the image I use a search with additional filtering, I get a return that shows that there is no data referring to this search, but the total is 5 
![Screenshot 2023-11-03 at 9 32 00 AM](https://github.com/DomDew/strapi-plugin-fuzzy-search/assets/84800849/c542f9b7-7e29-4f42-806d-4209d19533a5)

**Comment by DomDew** [comment]
Hey @Caio-Mendonca,

this seems to be an issue with Strapi overwriting the pagination meta for the GraphQL types - see [this issue](https://github.com/DomDew/strapi-plugin-fuzzy-search/issues/89) for updates.

**Comment by blueagler** [comment]
Hi, how is the update status of this issue? I've encountered this problem as well.
