### ISSUE TITLE
Is there a way or is it possible to get media fields in search result?

### ISSUE THREAD

**Issue by SujalLama** [DomDew/strapi-plugin-fuzzy-search#106]
Postman image:
I have a field called images in product content types. But it is not showing in the result?

<img width="879" alt="Screenshot 2023-11-09 at 08 55 48" src="https://github.com/DomDew/strapi-plugin-fuzzy-search/assets/71555740/e603bea1-3d90-428c-b3db-5376838579c2">

**Comment by DomDew** [comment]
Hey hey @SujalLama,

this sadly is not possible at the moment as this plugin currently does not support [population](https://docs.strapi.io/dev-docs/api/rest/populate-select#relations--media-fields). 

It is a feature I'd like to implement, however I don't have much time at the moment 😮‍💨.

PRs are always welcome though 😄.

See this [pinned issue](https://github.com/DomDew/strapi-plugin-fuzzy-search/issues/19) for updates.

**Comment by DomDew** [comment]
hey @SujalLama,

you should now be able to populate the images via a populate parameter on version v2.2.0 - see the docs for reference.

**Comment by gregg-cbs** [comment]
I am getting an error when trying to populate. The documentation is not clear on what config to add in order to populate.

I am getting the following error:
"Query params for model 'banner' were found, however this model is not configured in the fuzzy-search config"
