### ISSUE TITLE
Yup Validation getting wrong

### ISSUE THREAD

**Issue by Mahmoudgalalz** [DomDew/strapi-plugin-fuzzy-search#141]
![Screenshot 2023-12-26 at 5 03 01 AM](https://github.com/DomDew/strapi-plugin-fuzzy-search/assets/42272376/4413704f-ff5a-4e06-96d3-8e4ef83355fc)

I got this error even I have this file `plugin.ts`

![Screenshot 2023-12-26 at 5 03 42 AM](https://github.com/DomDew/strapi-plugin-fuzzy-search/assets/42272376/d7c71b0c-c75f-4f30-a384-826c19ef8ef8)

Latest Strapi Version

**Comment by DomDew** [comment]
Hey @Mahmoudgalalz,
Everythings looks correct in my eye.
I'll have a look if I can reproduce your issue...

**Comment by Mahmoudgalalz** [comment]
I use typescript, so I think it might help, there's smthing wrong for yup

**Comment by aldomeza-dev** [comment]
Getting the same exact error even if I only have the plugin enabled:

```javascript
"fuzzy-search": {
    enabled: true,
    config: {
      // See `Config` section.
    },
  },
```

**Comment by DomDew** [comment]
Hey @Mahmoudgalalz , @aldomeza-dev 
I can't reproduce your issue, does the error still occur for you?

**Comment by LassalleSimon** [comment]
I had the same issue and could solve it by adding `contentTypes: []` in the plugins.js file, as the error was caused by this attribute. Here is the full plugins.js file:
``` js
module.exports = () => ({
  "fuzzy-search": {
    enabled: true,
    config: {
      contentTypes: [],
    },
  },
});
```

**Comment by DomDew** [comment]
Only thing I can image is that for @Mahmoudgalalz typescript wasn't compiled correctly and thus the result plugin.js couldn't be loaded. For @aldomeza-dev, this is expected as you did not pass a `contentTypes` array to the config and the plugin thus throws a validation error through yup.
