### ISSUE TITLE
Support for the use of populate=*?

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [DomDew/strapi-plugin-fuzzy-search#15]
###  Postman: Example
The result of the query is not showing me the `directories.gallery` property.

<img width="846" alt="1" src="https://user-images.githubusercontent.com/21962584/172063960-62db5198-abd2-483b-b8be-20d24827669e.png">

###  Dependency versions: package.json

```json
"strapi-plugin-fuzzy-search": "^1.9.3",
"@strapi/strapi": "4.1.11",
```

**Comment by DomDew** [comment]
Hey @ChrisMichaelPerezSantiago,

this is not possible right now since the plugin is powered by a custom controller that registers a custom query for each content type. 

I do like the idea of being able to populate the response though and think I will add this feature. Please bear with me though, as I will have to look into how to sanitize the queries properly when they can be injected through the url. If you have a solid idea of how this can be achieved with Strapi out of the box feel free to let me know!

**Comment by pavelglac** [comment]
@DomDew Hi,
can I ask if there is any possibility to add populated fields into the response (not needed in search)? I have added the "populate" function in the lifecycle hook (beforeFindMany) so that the plugin gets the populated fields, but it just throws them away.

**Comment by raul-rtl** [comment]
Hi, @DomDew  any update on this?

Could you help or give me an idea, or confirm that it is not possible?

This is the plugin config
```
			contentTypes: [
				{
					uid: 'api::article.article',
					modelName: 'article',
					transliterate: false,
					queryConstraints: {
						where: {
							$and: [
								{
									publishedAt: { $notNull: true },
								},
							],
						},
					},
					fuzzysortOptions: {
						characterLimit: 500,
						threshold: -1000,
						limit: 15,
						keys: [
							{
								name: 'title',
								weight: 100,
							},
							{
								name: 'content',
								weight: -100,
							},
						],
					},
				},
			],
```

And I have this query that I do directly to strapi, where I search for articles that contain the tag name like the query. Tags are populated data from the article.
`http://localhost:1337/api/articles?filters[tags][name][$contains]={query}`

Can the previous one be merged with this one?
`api/fuzzy-search/search?query=`

Thanks in advance !!

**Comment by DomDew** [comment]
Hey hey @ChrisMichaelPerezSantiago, @raul-rtl and everyone else,

this should be possible now in v2.0.2

I'll close this issue so that we can use [this one ](https://github.com/DomDew/strapi-plugin-fuzzy-search/issues/19)for feedback and further discussion.
