### ISSUE TITLE
Results are not weighted correctly or in order

### ISSUE THREAD

**Issue by gregg-cbs** [DomDew/strapi-plugin-fuzzy-search#168]
Hi,

I am trying to up the "fuzziness" but it seems changing the threshold is not having the desired effect.

When I search a single word "burger" i get results. When I search two words "firehouse burger" things get weird and the results do not make sense based on my weights.

Look at this:
"name" has a weight of 10000.
"keywords" has a weight of 90.
"type" has a weight of -90.

The order of this results does not make sense. The word "firehouse" being searched is in the name of the 3rd card, yet it is 3rd and name has a weight of 10000? It almost appears to be in reverse.
![image](https://github.com/DomDew/strapi-plugin-fuzzy-search/assets/57114335/995c19ea-0126-4fd0-8603-9252bf2f5c25)

**Comment by gregg-cbs** [comment]
Here is another example where we are only fuzzy searching on the name property, we removed all the others. We have been testing for over an hour and something has to be incorrect somewhere in this package.

In this, undoubtedly "Firehouse" should be first, then "burger toaster" then "yummyfood".
![image](https://github.com/DomDew/strapi-plugin-fuzzy-search/assets/57114335/b6c6e1ff-cdbe-402b-a510-258290294bce)

Our config is:
```js
"fuzzy-search": {
  enabled: true,
  config: {
    contentTypes: [
      {
        uid: "api::vendor.vendor",
        modelName: "vendor",
        transliterate: false,
        fuzzysortOptions: {
          characterLimit: 300,
          threshold: -600,
          limit: 30,
          keys: [
            {
              name: "name",
              weight: 100,
            }
          ],
        }
      }
    ]
  }
}
```

**Comment by DomDew** [comment]
Seems correct to me. As `firehouse burger` isn't a substring of `firehouse` and couldn't reasonably be one "fuzzily" e.g. after a reasonable amount of mutations to the string `firehouse burger` it's score will likely be the lowest (`-9999`). As you are weighing the name rather high though, you are pushing the score beyond the threshold (-9999 + 10000 = 1). This will be applied to all the objects, so you are getting three results with the score of 1.

**Comment by gregg-cbs** [comment]
But how is it possible that a word that has nothing to do with the search term is rated higher then a word that does have the search term?

If I search "Firehouse Burger", how is it possible that the word that has nothing to do with that string comes first:
1. YummyFood
2. Burger Toaster
3. Firehouse

You say: "As firehouse burger isn't a substring of firehouse", neither is YummyFood and its somehow got the highest score?

**Comment by DomDew** [comment]
As I mentioned above, all your results will probably return a score of 1 and will thus be returned in the order they were obtained from the db (by Strapi defaults). If you were to lower the weight of the name to something like 100 (or anything below 10000 really), you wouldn't get any results, which would be expected. I wouldn't recommend setting the weights to such extreme values, as this will likely produce some false positives - or in your case always include any item.

**Comment by gregg-cbs** [comment]
Right so the issue here is that this project is not an elastic search, its a fuzzy filter and sort. Thats where i made a mistake. I will have to find something more suited.

Thanks for your time.
