### ISSUE TITLE
Can I search in populated fields?

### ISSUE THREAD

**Issue by kspacja** [DomDew/strapi-plugin-fuzzy-search#19]
I have a model:
```
Artist {
  name {String}
}

Album {
  name {String}
  artist {Artist}
}
```
Can I config plugin in a way, that if I search by artist's name in result I would see also albums, which belong to queried artist?

**Comment by DomDew** [comment]
Hey @kspacja ,
Yes, this should in fact be possible by passing a [population configuration](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/query-engine/populating.html) to the `queryConstraints` field in the configuration. To this field you can pass options to the underlying `findMany()` query in Strapis [query engine](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/query-engine-api.html)

**Comment by DomDew** [comment]
Ah I see what you mean. This is sadly not possible right now, since the queries on the server side are registered at build time and I currently haven't figured out a smart way on how to query/filter for nested relations at runtime.

[See this related issue](https://github.com/DomDew/strapi-plugin-fuzzy-search/issues/15)

I still think that this would be a cool feature, but didn't find a smooth and safe way of handling this (yet)

**Comment by kspacja** [comment]
I created a bit workaround. It is has flaws (like non-equality of type, entry should be santized before mapping)  , but I think in few cases it would be helpful.

I implemented extension to your plugin service, where I overwrote `getFilteredEntries` utils method:
```
const getFilteredEntries = async (locale, model) => {
  const { contentTypes } = getPluginService(strapi, "settingsService").get();
  const { mapEntry = (entry) => entry } = contentTypes.find(
    (entry) => entry.uid === model
  );

  const entries = await strapi.db
    .query(model)
    .findMany(buildDbQuery(locale, model));

  return entries.map(mapEntry);
};
```
As you can see there is optional `mapEntry` function passed via plugin configuration. Because of that, for example, I'm able to flatten an entry before fuzzysort is run.

In my case for albums `mapEntry` function looks like that:
```
(entry) => {
            return {
              ...entry,
              artist: entry.artist.name,
            };
          }
```
So if I query by `The Bealtes`, I got all albums.

**Comment by DomDew** [comment]
Hey @kspacja (and everyone else),

this should be possible now in v2.0.2

let me know if things aren't working out as expected or if anything is unclear!

**Comment by miloszwierucki** [comment]
Hello, I have a similar problem, although I don't know how to solve it,

I have 2 content-types: **academic-circle** and **faculty**, of course there is a 1-to-many relationship between them, is it already possible to search for  academic circles by the name of the faculty? If so, how to configure `plugins.ts` or how to send the appropriate query.

```
{
  "data": [
    {
      "id": 1,
      "attributes": {
        "name": "Kino",
        "faculty": {
          "data": {
            "id": 2,
            "attributes": {
              "name": "Wydział Fizyki Technicznej, Informatyki i Matematyki Stosowanej ",
              "abbreviation": "FTIMS",
            }
          }
        },
      }
    }]
}
```

**Request:**
`http://localhost:1337/api/fuzzy-search/search?query=ftims&populate[academic-circles][populate][0]=faculty
`

**Response:**
```
{
  "academic-circles": [],
  "faculties": [
    {
      "id": 2,
      "name": "Wydział Fizyki Technicznej, Informatyki i Matematyki Stosowanej ",
      "abbreviation": "FTIMS",
      "createdAt": "2023-11-24T16:04:07.616Z",
      "updatedAt": "2023-11-24T16:05:21.156Z",
      "publishedAt": "2023-11-24T16:05:21.153Z",
      "locale": "pl"
    }
  ]
}
```

**Request:**
`http://localhost:1337/api/fuzzy-search/search?query=ftims&populate[0]=faculty`

**Response:**
```
{
  "data": null,
  "error": {
    "status": 400,
    "name": "BadRequestError",
    "message": "Invalid query",
    "details": "Query params for model '0' were found, however this model is not configured in the fuzzy-search config"
  }
}
```

**Comment by nvitulli71** [comment]
I find that if I try to populate content like this `http://localhost:1337/api/fuzzy-search/search?query=test&populate[0]=content` and `content` is actually an array of objects I get `content: "[object Object]"`. Is there any way around this?
