### ISSUE TITLE
Declaring the "fuzzy-search" plugin after "graphql", produces Strapi throw an error.

### ISSUE THREAD

**Issue by Sunny-Pirate** [DomDew/strapi-plugin-fuzzy-search#20]
Hi all,

as the title says when I declare fuzzy-search plugin after the graphql, cause an error.
![with-error](https://user-images.githubusercontent.com/109725967/188807874-672b6062-1708-4ce0-b9b1-d4bf4c07cbc4.png)

Instead, when declaring the plugin before all works as expected.

**Comment by DomDew** [comment]
Hey @Sunny-Pirate ,
thanks for bringing this to my attention! I will have a look as soon as I have some time 👍

**Comment by DomDew** [comment]
Fixed in 1.9.5

**Comment by DomDew** [comment]
@all-contributors please add @Sunny-Pirate for bug
