### ISSUE TITLE
Strapi is unable to start with `npm run dev`

### ISSUE THREAD

**Issue by signorekai** [DomDew/strapi-plugin-fuzzy-search#27]
```
[2022-10-05 16:20:47.786] debug: ⛔️ Server wasn't able to start properly.
[2022-10-05 16:20:47.788] error: strapi-server.js is invalid for 'plugin::fuzzy-search'.
this field has unspecified keys: default
Error: strapi-server.js is invalid for 'plugin::fuzzy-search'.
this field has unspecified keys: default
```

This only happens with `v1.10.0`. Downgrading to `v1.9.5` works.

**Comment by DomDew** [comment]
hey @signorekai,
thanks for the bug report!
Would you mind sharing on which version of Strapi you are? 

I tested against existing projects and on a fresh installation of strapi (both as js and ts projects) and couldn't reproduce your error (using the example config from the readme). Do you have any other plugins installed? And are you using GraphQL or REST?

**Comment by philgran** [comment]
I was able to work around this issue by adding `default` as a key in the `.shape()` method of this file in the Strapi package in node_modules:
`/node_modules/@strapi/strapi/lib/core/domain/module/validation.js`
So mine looks like this:
```
const strapiServerSchema = yup
  .object()
  .shape({
    bootstrap: yup.mixed().isFunction(),
    destroy: yup.mixed().isFunction(),
    register: yup.mixed().isFunction(),
    config: yup.object(),
    routes: yup.lazy(value => {
      if (Array.isArray(value)) {
        return yup.array();
      } else {
        return yup.object();
      }
    }),
    controllers: yup.object(),
    services: yup.object(),
    policies: yup.object(),
    middlewares: yup.object(),
    contentTypes: yup.object(),
    default: yup.object(), // <-- Added this right here
  })
  .noUnknown();
```
Removing the `.noUnknown();` would probably also solve this problem.

THIS IS NOT A PERMANENT FIX, I just did this to get the server running. Modifying the Strapi source code is not a good idea, as this could have unintended side effects.

**Comment by DomDew** [comment]
@philgran thanks for adding on to this.
Seems indeed to be an issue with the Strapi version 4.1.8. 

I'll see if I can find a workaround. In the meantime I'd suggest you update your Strapi version if you can, which should solve this issue.

@all-contributors please add @signorekai  for bug
@all-contributors please add @philgran  for bug

**Comment by DomDew** [comment]
@all-contributors please add @philgran  for bug

**Comment by DomDew** [comment]
@all-contributors please add @philgran for bug

**Comment by philgran** [comment]
Can confirm, updating to latest Strapi (4.4.6) fixes this issue.

**Comment by DomDew** [comment]
Alright, seems to be an issue resulting from me porting the codebase to Typescript. As a result Strapi Version pre Typescript support will unfortunately crash on mount. 

All Strapi Versions >4.3.0 should work fine with this Plugin. I'll see if I can find a way keeping this Plugin downwards compatible. Otherwise I guess I'll have to introduce this is a breaking change...

**Comment by signorekai** [comment]
Hadn't noticed your reply @DomDew until now, apologies. Not sure I've done anything to deserve being added as a contributor though 😅 .

And yes, I was using `4.1.8` when reporting the issue.

**Comment by DomDew** [comment]
@signorekai a bug report is always worth being added as a contributor in my book. I would've never found this bug without you mentioning it 😅.
