### ISSUE TITLE
Feature request: a way to search by model

### ISSUE THREAD

**Issue by matepaiva** [DomDew/strapi-plugin-fuzzy-search#3]
Hello, first of all, wonderful job here, congratz! 

I need two things for my project:
1. To search in all models, as your plugin does right now ✅
2. To have the option (a param or a different endpoint) to search in a specific model, and I don't know if that is possible 🤔 

So...
a) If it's possible, can you tell me how? Maybe I can contribute with documentation.
b) If it's not possible, is it a feasible feature to add to the plugin? If so and if you can provide me some guidance, I can contribute with the feature.

Thank you!

**Comment by DomDew** [comment]
Hey hey,
thank you for opening this issue!

As of now it is not possible to query only for a specific model.
I think we could try to pass a model as a query parameter and if the parameter is passed only return entries for this model. This should be doable for both the REST endpoint as well as the graphql type.

You could have a look at the fuzzySearchService.js an see if you can find a way to only return entries for a model specified through (for example) a modelName parameter that you can both pass from the REST controller as well as the graphql type.

Feel free to open a PR if you think you are up for the challenge 😄  I'm here if you need help and If you think it's too much right now I can see if I can whip something up in the near future 🤔

**Comment by matepaiva** [comment]
Nice! I will try it later, probably this weekend, and I give you some feedback. Thanks!

**Comment by DomDew** [comment]
Hey @matepaiva,

I released a way to filter by content types for a request in the [newest beta release](https://www.npmjs.com/package/strapi-plugin-fuzzy-search/v/1.11.0-beta.1). I think this should suite your needs!

Please refer to [this thread](https://github.com/DomDew/strapi-plugin-fuzzy-search/issues/41) with any feedback 😄
