### ISSUE TITLE
strapi-plugin-fuzzy-search@1.10.2: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "18.8.0"

### ISSUE THREAD

**Issue by dcromster** [DomDew/strapi-plugin-fuzzy-search#32]
Error in subject :)

**Comment by DomDew** [comment]
Hey @dcromster ,

the plugin only accepts node version that are [supported as per the Strapi documentation](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/installation/cli.html). Meaning, only lts versions up to v16 are supported. It appears that you are on version 18.8.0, which is producing the error. I'd suggest you move to node v16. 

Feel free to let me know if you have any other issues!
