### ISSUE TITLE
Feature request: Populate fields

### ISSUE THREAD

**Issue by rotarrares** [DomDew/strapi-plugin-fuzzy-search#4]
Hello! I would like to populate the fields of the results. 
I've tried adding the populate object to the "whereConstraints" but it's not working.

**Comment by rotarrares** [comment]
I prepared a commit to change the whereConstraints to queryConstraints so we can do populate. Is this repository open to contributors? Apologies that I don't know where to look, this is my first contribution. 
`
if (locale) {
    if (queryConstraints.where) {
      return {...queryConstraints, where: { ...queryConstraints.where, locale: locale, } };
    }
    return {...queryConstraints, where: {  locale: locale, } };
  }
`

**Comment by DomDew** [comment]
Hey @rotarrares,

thank you for your feature request! 
This is a great addition and I will add the feature for the nest version update. 
Should I take too long, feel free to open a PR. Adding this feature will require some changes to the schema, as well as the getFilteresEntries.js util.

**Comment by rotarrares** [comment]
Thank you @DomDew for the quick response and support,

I added the queryConstraints to schema as as simple object. should I specify the where and populate fields too?

**Comment by DomDew** [comment]
@rotarrares I think a simple object will do, as there are too many settings to keep track off in my book. I will have a look at your PR tomorrow, thank you so much!

**Comment by DomDew** [comment]
Added in 1.9.0

Thank you @rotarrares for the great PR!
