### ISSUE TITLE
Pagination and filtering

### ISSUE THREAD

**Issue by luzadev** [DomDew/strapi-plugin-fuzzy-search#41]
Hi its possibile to have pagination of the results?

**Comment by DomDew** [comment]
Hey @luzadev ,
sorry I took so long to respond. I think this would be a pretty nice feature and I think I'll implement it once I have some more time on my hands. I will let you know when it's released!

**Comment by DomDew** [comment]
Hey @luzadev and everyone else,

pagination as well as filtering by content type is now available in the [beta 1.11.0](https://www.npmjs.com/package/strapi-plugin-fuzzy-search/v/1.11.0-beta.1). Please leave any feedback you have in this thread and I'll see what can be done 😄.

**Comment by DomDew** [comment]
Released in v1.11.0
