### ISSUE TITLE
Meta GRAPHQL

### ISSUE THREAD

**Issue by vadim656** [DomDew/strapi-plugin-fuzzy-search#43]
When adding meta > pagination > total to the search, the search stops working, maybe I'm doing something wrong?

`query SEARCH_ANALIZES($S_VALUE: String!) {
  search(query: $S_VALUE) {
    analizies {
      meta {
        pagination{
          total
        }
      }
      data {
        id
        attributes {
          Name
          Art
          TimeDone
          Price
          Complecs
          Active
          Tags
          Desc
        }
      }
    }
  }
}`

answer --

`"errors": [
    {
      "message": "Model undefined not found",
      "locations": [
        {
          "line": 6,
          "column": 9
        }
      ],
      "path": [
        "search",
        "analizies",
        "meta",
        "pagination"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Model undefined not found",
            "    at Database.query (/mnt/d/work/albvt_admin/node_modules/@strapi/database/lib/index.js:44:13)",
            "    at Object.count (/mnt/d/work/albvt_admin/node_modules/@strapi/strapi/lib/services/entity-service/index.js:119:15)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at async Object.count (/mnt/d/work/albvt_admin/node_modules/@strapi/strapi/lib/services/entity-service/index.js:310:20)",
            "    at async resolve (/mnt/d/work/albvt_admin/node_modules/@strapi/plugin-graphql/server/services/internals/types/response-collection-meta.js:28:27)"
          ]
        }
      }
    }
  ],
  "data": {
    "search": {
      "analizies": null
    }
  }
}`

**Comment by DomDew** [comment]
Hey @vadim656 ,
thanks for bringing this up!

I think the error you are getting comes up because at the moment there isn't a way to paginate the response.
See [this related issue](https://github.com/DomDew/strapi-plugin-fuzzy-search/issues/41).

I plan on adding pagination in the future but I can't say when I will have the time to implement that feature...

**Comment by DomDew** [comment]
Hey @vadim656,

pagination is now available in the newest beta. Please refer to [this thread](https://github.com/DomDew/strapi-plugin-fuzzy-search/issues/41) for all pagination related issues.
