### ISSUE TITLE
How do I populate the query with images, components, relations, dynamic zones

### ISSUE THREAD

**Issue by woomiz** [DomDew/strapi-plugin-fuzzy-search#45]
I tried to retrieve the images using the query : 
`{{baseURL}}/fuzzy-search/search?query=product&populate=%2A`

and it resulted in giving me normal fields only.

**Comment by DomDew** [comment]
Hey @woomiz ,
Population isn't possible yet. I plan on adding this feature in the future when I have more time.

See this thread: https://github.com/DomDew/strapi-plugin-fuzzy-search/issues/41

**Comment by woomiz** [comment]
Yeah its fine, this feature costed me. So did everything with meilisearch. I give fuzzy-search a try because its looks so simple to use.

**Comment by insivika** [comment]
This is crucial! Can we get this on the road map please 🙏
