### ISSUE TITLE
Support accents / diatrics? (é è à ç etc...)

### ISSUE THREAD

**Issue by maximelebreton** [DomDew/strapi-plugin-fuzzy-search#51]
Hello @DomDew,

I'm using your plugin for a french website and this language use accents / diatrics.

So when i'm searching `identite` keyword, and in my content the word is `identité`, I have no results.

The author of **fuzzysort** suggest this solution in this comment: https://github.com/farzher/fuzzysort/issues/23#issuecomment-366492221, but I dont know how to implement it through your plugin?

Any suggestion?

Thanks!

**Comment by DomDew** [comment]
Hey @maximelebreton,

Thanks for bringing this up!

do you have transliteration enabled? That might solve the problem you are facing.

If you have it enabled and are still not getting results, than I'd say this would have to be a new feature...

**Comment by maximelebreton** [comment]
hello @DomDew, thanks for your time, and sorry for my late response,

I have only one language on this site (french), but even if I had activated transliteration, it would not solve the problem,
because I want results from a french word without accent (input: `identite` -> output: `identité`).

Thanks!

**Comment by jfrancoeur** [comment]
Why does Strapi does not include diacritics insensitive search by default :(
