### ISSUE TITLE
Can't install in Node 18

### ISSUE THREAD

**Issue by jesusr00** [DomDew/strapi-plugin-fuzzy-search#54]
I'm training to install on Node 18.13.0 and Yarn 1.22.19 but fails with the next error:
error strapi-plugin-populate-deep@1.1.2: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "18.13.0"
error Found incompatible module.

**Comment by DomDew** [comment]
Hey @jesusr00 

thanks for opening this issue! I've updated the package json to be in sync with the strapi requirements. It should work on the newest release.

The specific error you mentioned seems to be raised from the strapi-plugin-populate-deep  as well though 😅 

@all-contributors please add @jesusr00 for bug
