### ISSUE TITLE
Query always return single type item

### ISSUE THREAD

**Issue by soapwong703** [DomDew/strapi-plugin-fuzzy-search#57]
No matter the query params I type, it will always return the single type if the entry exists.

![image](https://user-images.githubusercontent.com/68498079/218944271-60d41dcf-0dc3-4509-850e-d2b5a00fea2a.png)

```
somepage/schema.json:
{
  "kind": "singleType",
  "collectionName": "somepages",
  "info": {
    "singularName": "somepage",
    "pluralName": "somepages",
    "displayName": "somepage"
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "title": {
      "type": "string"
    }
  }
}
```

**Comment by DomDew** [comment]
Hey @soapwong703 ,

I'd suggest you introduce a threshold value (start with somethink like -3000) and adjust from there. This should solve your problem.

**Comment by soapwong703** [comment]
Hi @DomDew!

Thank you for helping me out. Threshold value solved my issue.  However should the threshold value be mandatory since without it single type entry will always return a item?

**Comment by DomDew** [comment]
Yeah, that's a good idea. I will make that change when I roll out the next set of features 👌.
