### ISSUE TITLE
very slow performance - what am I doing wrong?

### ISSUE THREAD

**Issue by nphardorworse** [DomDew/strapi-plugin-fuzzy-search#58]
Hi,

I think I'm missing something regarding the setup, since even the simplest query takes more than 60**sec** to run (vs <300ms for the same query using just a regular strapi path).

I tried to keep it simple, following the documentation:

```
"fuzzy-search": {
    enabled: true,
    config: {
      contentTypes: [
        {
          uid: "api::x.x",
          modelName: "x",
          transliterate: false,
          fuzzysortOptions: {
            characterLimit: 50,
            threshold: -100,
            limit: 10,
            keys: [
              {
                name: "field1",
                weight: 100,
              },
              {
                name: "field2",
                weight: 300,
              }
            ],
          },
        }],
      }
    }```

Is there anything I can change to improve the performance or make it useable otherwise?

The table is not crazy big: 80k rows x 84 columns (most numerical). The two fields I want to query are also just a short text fields.  

I'd appreciate any guidance, thanks!

**Comment by DomDew** [comment]
Hey @nphardorworse ,

judging from your config everything seems to be in order.

I've never really tested the plugin against a huge dataset and I could have a look once I'm done with the current set of changes I'm implementing.

I do think however that there isn't much to be gained performance wise. If performance is a concern and you are working with large datasets, I'd argue that something like a meilisearch or elasticsearch instance is more suitable for your use case.

Sorry that I can't be of much help at this point!

Feel free to take a look at the src-code, maybe you can find some obvious bottlenecks and could through together a PR?

**Comment by nphardorworse** [comment]
Hey, thanks for the reply! I did indeed move to meilisearch. 
My wild guess would be that this plugin is probably reindexing everything from scratch with every call, this is why it takes so long. In principle, I'd love to contribute and play around, but at this moment I'm a bit (read: a lot) behind on my deadlines, so I honestly don't have time. Sorry!
