### ISSUE TITLE
poor results even with very close strings and low threshold

### ISSUE THREAD

**Issue by vitormanfredini** [DomDew/strapi-plugin-fuzzy-search#59]
Hi,

After setting up the plugin (version 1.10.4) on strapi (version 4.5.1) I can't seem to get good results even after lowering the threshold a lot.
I currently have 11 entries in the database with the word "abridor" in them, like "Abridor amarelo", "chaveiro abridor", "abridor adesivado", etc...
But when I try to search for "abrdor" or "abredor", I get zero results.
Some variations return some results but still very few, like "abridos" gets 1 result.

Here's my config:
```
"fuzzy-search": {
    enabled: true,
    config: {
      contentTypes: [
        {
          uid: "api::material.material",
          modelName: "material",
          transliterate: false,
          fuzzysortOptions: {
            characterLimit: 500,
            threshold: -8000,
            limit: 9999,
            keys: [
              {
                name: "nome",
                weight: 100,
              }
            ],
          },
        },
      ],
    },
  },
```

Any ideas?

Thank you!
Vítor

**Comment by DomDew** [comment]
Hey @vitormanfredini ,

everything seems to be set up correctly on your end.

In some cases the algorithm ([fuzzysort](https://github.com/farzher/fuzzysort)) will behave a bit strange, when it comes to getting good results for typos. Between [fuse](https://fusejs.io/) and [fuzzysort](https://github.com/farzher/fuzzysort) I found the latter to produce more reliable results though, especially when searching through longer strings, where I found fuse to return a lot of false positives.

Sorry I can't be much of help. I think that if typo tolerance (and having sophisticated configuration options) something like [meilisearch](https://docs.meilisearch.com/learn/configuration/typo_tolerance.html#configuring-typo-tolerance) may be the more suitable option for your use case.
