### ISSUE TITLE
Filter Parameter/Arg

### ISSUE THREAD

**Issue by Markkop** [DomDew/strapi-plugin-fuzzy-search#62]
Hey, DomDew. Awesome work you have done on this plugin!

Is filtering the results by other fields, like Category, possible?

For example, for a simple search, we have
```
api/blog-posts?sort=publishedAt:desc&populate[populate]=*&filters[$or][0][title][$contains][0]=fire&filters[$or][1][content][$contains][0]=fire
```

Which would be converted to

```
api/fuzzy-search/search?query=fire&filters[contentTypes]=blog-posts
```

But for the category, I'm not sure how I would convert the following search
```
api/blog-posts?sort=publishedAt:desc&populate[populate]=*&filters[$or][0][title][$contains][0]=fire&filters[$or][1][content][$contains][0]=fire&filters[$and][1][Category][id][$eq]=32
```

I don't know much about Strapi yet, but if this is a `populate` filter thing, would it relate to the pinned issues?
Thanks!

**Comment by DomDew** [comment]
Hey @Markkop,

thank you so much for opening this issue!

This is sadly not possible at the moment, but I'm currently working on a feature that would make what you are asking for possible.

I have something along the lines of:
`... filters[yourContentType][$or][0][title][$contains][0]=fire`
in mind.

Same thing would go for population.

Would something like that make sense for you?

Generally I'm thinking of moving a lot more of the configuration to query params/graphql args for a version 3.

This might take some time though, as I currently have a lot going on 😅

**Comment by uni-vinay-p** [comment]
Will this upcoming feature enable us to search with data from relational collection?

**Comment by Markkop** [comment]
> Would something like that make sense for you?

I think it would. I'm more interested in the following part of the filter:

```
filters[$and][1][Category][id][$eq]=32
``
`

But I believe that's something that your next feature will support.

Thanks for your response!

**Comment by DomDew** [comment]
@Markkop,

yes I think this should work.

**Comment by johngribbin** [comment]
@DomDew Thanks for the plugin! Solving a lot of headaches for me that I have had with Meilisearch tbh. I see you have pagination included in the current pre-release. Do you recommend running that in production? Or should we wait until you cut a release that includes it? And on that point, any timeline? Thanks!!

**Comment by DomDew** [comment]
Hey @johngribbin,
I'm still looking for feedback for the pagination feature. I would consider it stable, but I haven't heard back from other people than me that are using the pagination feature 😅.

I will release the pagination in one go with the filters and the like. Hopefully somewhen this month.

**Comment by DomDew** [comment]
Hey @Markkop, @johngribbin!

Feature has been released in v.1.11.0
Let me know if you have any issues!
