### ISSUE TITLE
Multiple keys to search not working

### ISSUE THREAD

**Issue by rotarrares** [DomDew/strapi-plugin-fuzzy-search#7]
All the search results are matching only for the first key declared in plugins.
After some debugging it was found that in the score function the only key checked for result is the first key a[0]. The score function parameter contains an array with an index for each key. 
` scoreFn: (a) =>
            Math.max(
              ...model.fuzzysortOptions.keys.map((key) =>
                a[0] ? a[0].score + key.weight : -1000
              )
            ),
`
So to make it work with multiple keys and adjust weights correctly I had to change the code to this: 
`
scoreFn: (a) =>
            Math.max(
              ...model.fuzzysortOptions.keys.map((key, index) =>
                (a[index] ? a[index].score + key.weight : -999999)
              )
            )
`
Notice I also set the minimum score (if the key has no result) to a lower value, because some of the searches that I want to return are just bellow -5000. I tried with Number.MIN_VALUE but the max function doesn't work with it

**Comment by DomDew** [comment]
Hey @rotarrares, nice catch!
This should be fixed in 1.8.3
