### ISSUE TITLE
Bug TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by prborisov17** [DomDew/strapi-plugin-fuzzy-search#73]
error: Cannot read properties of undefined (reading 'offers')
TypeError: Cannot read properties of undefined (reading 'offers')
    at /home/pavel/GIT/cms.oekmarket.ru/node_modules/strapi-plugin-fuzzy-search/dist/server/controllers/search-controller.js:34:91

Plise set default value for filtersQuery in search-controller.js

const { query, pagination, filters: filtersQuery = {}, locale } = ctx.query;

**Comment by DomDew** [comment]
Hey @prborisov17,

thank you for reporting this bug and sorry that this somehow slipped past...

@all-contributors please add @prborisov17  for bug

**Comment by DomDew** [comment]
@all-contributors please add @prborisov17 for bug

**Comment by michaelroth-xx** [comment]
Can you please also fix this for 1.x?
