### ISSUE TITLE
Yup Conflicting Peer Dependency 

### ISSUE THREAD

**Issue by insivika** [DomDew/strapi-plugin-fuzzy-search#86]
Hello, 
When installing the plugin I get a dependency error:

Found: yup@0.32.11
Wants: yup@"^1.0.0"

I'm using strapi v4.10.5 and installing strapi-plugin-fuzzy-search v^1.11.0

**Comment by DomDew** [comment]
Hey hey @insivika,

thanks for bringing this up. Should be fixed in v1.11.3 and 2.0.4. Note that these versions require you to run a Strapi version >= 4.11.4
