### ISSUE TITLE
Can I use this plugin with entity service to query? And If so please can you provide an sample code for it?

### ISSUE THREAD

**Issue by toshits** [DomDew/strapi-plugin-fuzzy-search#90]

**Comment by DomDew** [comment]
Hey @toshits,

I'm afraid I don't understand what you mean?

This Plugin provides a REST Endpoint and a GraphQl Type which you can use for fuzzy-searching in content types.

Do you mean that you want to perform a fuzzy search whilst querying for date with the entityService api in custom code? That wouldn't be possible, but feel free to take a look at the source code of this plugin to see how we are doing it.

**Comment by toshits** [comment]
@DomDew Yup, I meant using plugin inside custom api. I wanted to fetch relation type column. Sure I will look into the code.
