### ISSUE TITLE
Filtering for only published entries not working

### ISSUE THREAD

**Issue by piterson-satio** [DomDew/strapi-plugin-fuzzy-search#91]
Hello, we're using this fuzzy search plugin for our strapi project for the site search, but recently we discovered that it doesn't filter out unpublished/draft entries by default, however even by adding filters to publishedAt and publicationState, the draft entries are still showing up.

Request:
`/api/fuzzy-search/search?query=tes&filters[contentTypes]=static-pages&filters[static-pages][publishedAt][$notNull]=true`

Result:
```js
{
  "static-pages": [
    {
      "id": 9,
      "title": "tes page",
      "description": "tes",
      "slug": "tes-page",
      "createdAt": "2023-07-28T08:58:55.933Z",
      "updatedAt": "2023-07-28T08:58:55.933Z",
      "publishedAt": null, // note that the publishedAt is null
      "attached_seo_meta_data": null,
      "contents": []
    }
  ]
}
```

Here's the config object for the collection type we used in `/config/plugins.js` in case it's relevant.
```js
"fuzzy-search": {
    enabled: true,
    config: {
      contentTypes: [
        // ...
        {
          uid: "api::static-page.static-page",
          modelName: "static-page",
          queryConstraints: {
            populate: true,
          },
          fuzzysortOptions: {
            characterLimit: 500,
            threshold: -1000,
            limit: 10,
            keys: [
              {
                name: "title",
                weight: 100,
              },
              {
                name: "description",
                weight: 100,
              },
              {
                name: "contents",
                weight: 100,
              },
            ],
          },
        },
      ],
    },
  }
```

Thanks in advance!

**Comment by DomDew** [comment]
Hey @piterson-satio,

thank you for reporting this bug! I just tried to reproduce your example but for me everything works as expected.

With `/api/fuzzy-search/search?query=unpublished&filters[contentTypes]=with-spaces&filters[with-spaces][publishedAt][$notNull]=true` I get the expected result of:
```json
{
  "with-spaces": [ ]
}
```

Could you specify which versions of the package and of Strapi you are on?

**Comment by piterson-satio** [comment]
Hello, thanks for the reply. Currently we're using Strapi v4.9.0 with the version of the package in the package.json as `1.11.0-beta.1`. Do you have a recommended version of the fuzzy search plugin that would be compatible for our current strapi version? Or do we have to use the newest version for this to work?

**Comment by piterson-satio** [comment]
Hi, the v2.0.3 of the plugin works for our v4.9.0 strapi project, thanks a lot for the help!
