### ISSUE TITLE
Relation population on the search result

### ISSUE THREAD

**Issue by quierosol** [DomDew/strapi-plugin-fuzzy-search#99]
Since queryConstraints are removed from the configuration in the last version of the plugin is there other possibility to populate nested data in the returned search results.

**Comment by DomDew** [comment]
Hey @quierosol,

`queryConstraints` have been removed and substituted by passing in filters as a query parameter with >v2.0.0: [See docs](https://github.com/DomDew/strapi-plugin-fuzzy-search#filters)

**Comment by quierosol** [comment]
Hello @DomDew,
Firstly thank you for your fast response but how can I populate related content types for the content types passed in the filters? Is there a way for me to populate nested content types?

**Comment by DomDew** [comment]
Hey @quierosol,
this sadly is not possible at the moment but something I'd like to be working on when I have more time, [see this issue](https://github.com/DomDew/strapi-plugin-fuzzy-search/issues/19).
